import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function AboutPage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <h1 className="text-4xl font-bold mb-8">Understanding Voice Deepfakes</h1>
      
      <div className="space-y-8 text-muted-foreground leading-relaxed">
        <section className="glass-panel p-8 rounded-xl">
          <h2 className="text-2xl font-bold text-white mb-4">What is an Audio Deepfake?</h2>
          <p className="mb-4">
            An audio deepfake is a synthetic voice recording generated by artificial intelligence. Using techniques like voice cloning, an attacker can train a machine learning model on a few minutes of a person's speech and then generate new audio making it sound as if that person is saying anything the attacker types.
          </p>
        </section>

        <section className="glass-panel p-8 rounded-xl">
          <h2 className="text-2xl font-bold text-white mb-4">How Vocal for Local Works</h2>
          <p className="mb-4">
            Vocal for Local uses deep learning to detect the subtle acoustic artifacts left behind by generative AI models. When a voice is synthesized, it often lacks the natural respiratory patterns and high-frequency harmonic structures of a real human vocal tract.
          </p>
          <p>
            Our pipeline extracts Mel-frequency cepstral coefficients (MFCCs) and other spectral features, feeding them into a Convolutional Neural Network (CNN) trained on large datasets of real and synthetic speech.
          </p>
        </section>

        <section className="glass-panel p-8 rounded-xl">
          <h2 className="text-2xl font-bold text-white mb-4">Limitations</h2>
          <p className="mb-4">
            Machine-learning-based audio classification is probabilistic and may produce incorrect results. As generative models improve, detection becomes a continuous arms race. This tool should be used as one signal in a broader forensic investigation, not as absolute proof of authenticity.
          </p>
        </section>
      </div>
    </div>
  );
}
